ALTER TABLE companies
  ADD COLUMN working_url TEXT,
  ADD COLUMN site_name TEXT,
  ADD COLUMN last_checked_at TIMESTAMPTZ,
  ADD COLUMN attempts INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN should_retry BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN all_sites_checked BOOLEAN NOT NULL DEFAULT FALSE;

