CREATE TABLE IF NOT EXISTS wttj_scrape_meta_data (
  id INTEGER PRIMARY KEY DEFAULT 1 CHECK(id = 1),
  next_page INTEGER NOT NULL DEFAULT 0,
  completed BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
