ALTER TABLE IF EXISTS companies
  ADD COLUMN greenhouse_checked BOOLEAN NOT NULL DEFAULT FALSE, 
  ADD COLUMN team_tailor_checked BOOLEAN NOT NULL DEFAULT FALSE, 
  ADD COLUMN lever_checked BOOLEAN NOT NULL DEFAULT FALSE, 
  ADD COLUMN workable_checked BOOLEAN NOT NULL DEFAULT FALSE,
  DROP COLUMN IF EXISTS all_sites_checked;

