// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package khadgar

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

// PersonalisedCompaniesPersonalisedCompaniesCompany includes the requested fields of the GraphQL type Company.
type PersonalisedCompaniesPersonalisedCompaniesCompany struct {
	Name             string                                                `json:"name"`
	ShortDescription string                                                `json:"shortDescription"`
	Size             PersonalisedCompaniesPersonalisedCompaniesCompanySize `json:"size"`
}

// GetName returns PersonalisedCompaniesPersonalisedCompaniesCompany.Name, and is useful for accessing the field via an interface.
func (v *PersonalisedCompaniesPersonalisedCompaniesCompany) GetName() string { return v.Name }

// GetShortDescription returns PersonalisedCompaniesPersonalisedCompaniesCompany.ShortDescription, and is useful for accessing the field via an interface.
func (v *PersonalisedCompaniesPersonalisedCompaniesCompany) GetShortDescription() string {
	return v.ShortDescription
}

// GetSize returns PersonalisedCompaniesPersonalisedCompaniesCompany.Size, and is useful for accessing the field via an interface.
func (v *PersonalisedCompaniesPersonalisedCompaniesCompany) GetSize() PersonalisedCompaniesPersonalisedCompaniesCompanySize {
	return v.Size
}

// PersonalisedCompaniesPersonalisedCompaniesCompanySize includes the requested fields of the GraphQL type CompanySize.
type PersonalisedCompaniesPersonalisedCompaniesCompanySize struct {
	Value string `json:"value"`
}

// GetValue returns PersonalisedCompaniesPersonalisedCompaniesCompanySize.Value, and is useful for accessing the field via an interface.
func (v *PersonalisedCompaniesPersonalisedCompaniesCompanySize) GetValue() string { return v.Value }

// PersonalisedCompaniesResponse is returned by PersonalisedCompanies on success.
type PersonalisedCompaniesResponse struct {
	PersonalisedCompanies []PersonalisedCompaniesPersonalisedCompaniesCompany `json:"personalisedCompanies"`
}

// GetPersonalisedCompanies returns PersonalisedCompaniesResponse.PersonalisedCompanies, and is useful for accessing the field via an interface.
func (v *PersonalisedCompaniesResponse) GetPersonalisedCompanies() []PersonalisedCompaniesPersonalisedCompaniesCompany {
	return v.PersonalisedCompanies
}

// __PersonalisedCompaniesInput is used internally by genqlient
type __PersonalisedCompaniesInput struct {
	Offset      int    `json:"offset"`
	Limit       int    `json:"limit"`
	CompanyName string `json:"companyName"`
}

// GetOffset returns __PersonalisedCompaniesInput.Offset, and is useful for accessing the field via an interface.
func (v *__PersonalisedCompaniesInput) GetOffset() int { return v.Offset }

// GetLimit returns __PersonalisedCompaniesInput.Limit, and is useful for accessing the field via an interface.
func (v *__PersonalisedCompaniesInput) GetLimit() int { return v.Limit }

// GetCompanyName returns __PersonalisedCompaniesInput.CompanyName, and is useful for accessing the field via an interface.
func (v *__PersonalisedCompaniesInput) GetCompanyName() string { return v.CompanyName }

// The query executed by PersonalisedCompanies.
const PersonalisedCompanies_Operation = `
query PersonalisedCompanies ($offset: Int!, $limit: Int!, $companyName: String!) {
	personalisedCompanies(offset: $offset, limit: $limit, companyName: $companyName) {
		name
		shortDescription
		size {
			value
		}
	}
}
`

func PersonalisedCompanies(
	ctx_ context.Context,
	client_ graphql.Client,
	offset int,
	limit int,
	companyName string,
) (data_ *PersonalisedCompaniesResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "PersonalisedCompanies",
		Query:  PersonalisedCompanies_Operation,
		Variables: &__PersonalisedCompaniesInput{
			Offset:      offset,
			Limit:       limit,
			CompanyName: companyName,
		},
	}

	data_ = &PersonalisedCompaniesResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
