// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: companies.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUncheckedCompanies = `-- name: GetUncheckedCompanies :many
SELECT id, url_safe_name FROM companies
  WHERE site_name is NULL
  ORDER BY attempts ASC, id ASC
`

type GetUncheckedCompaniesRow struct {
	ID          int64
	UrlSafeName string
}

func (q *Queries) GetUncheckedCompanies(ctx context.Context) ([]GetUncheckedCompaniesRow, error) {
	rows, err := q.db.Query(ctx, getUncheckedCompanies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUncheckedCompaniesRow
	for rows.Next() {
		var i GetUncheckedCompaniesRow
		if err := rows.Scan(&i.ID, &i.UrlSafeName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCompany = `-- name: InsertCompany :exec
INSERT INTO companies(name, url_safe_name, short_description, size)
VALUES (
  $1,
  regexp_replace($2, '-[0-9]+$', ''), -- Removes dash and number suffix
  $3,
  $4
)
ON CONFLICT (name) DO NOTHING
`

type InsertCompanyParams struct {
	Name             string
	UrlSafeName      string
	ShortDescription string
	Size             string
}

func (q *Queries) InsertCompany(ctx context.Context, arg InsertCompanyParams) error {
	_, err := q.db.Exec(ctx, insertCompany,
		arg.Name,
		arg.UrlSafeName,
		arg.ShortDescription,
		arg.Size,
	)
	return err
}

const updateCompanyJobSite = `-- name: UpdateCompanyJobSite :exec
UPDATE companies
SET 
  working_url = $1,
  site_name = $2,
  last_checked_at = NOW(),
  attempts = attempts + 1,
  updated_at = NOW()
WHERE name = $3
`

type UpdateCompanyJobSiteParams struct {
	WorkingUrl pgtype.Text
	SiteName   pgtype.Text
	Name       string
}

func (q *Queries) UpdateCompanyJobSite(ctx context.Context, arg UpdateCompanyJobSiteParams) error {
	_, err := q.db.Exec(ctx, updateCompanyJobSite, arg.WorkingUrl, arg.SiteName, arg.Name)
	return err
}
