// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: companies.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertCompany = `-- name: InsertCompany :exec
INSERT INTO companies(name, short_description, size, url_safe_name)
VALUES (
  $1,
  $2,
  $3,
  regexp_replace($4, '-[0-9]+$', '')
)
ON CONFLICT (name) DO NOTHING
`

type InsertCompanyParams struct {
	Name             string
	ShortDescription string
	Size             string
	UrlSafeName      string
}

func (q *Queries) InsertCompany(ctx context.Context, arg InsertCompanyParams) error {
	_, err := q.db.Exec(ctx, insertCompany,
		arg.Name,
		arg.ShortDescription,
		arg.Size,
		arg.UrlSafeName,
	)
	return err
}

const updateCompanyJobSite = `-- name: UpdateCompanyJobSite :exec
UPDATE companies
SET 
  working_url = $1,
  site_name = $2,
  last_checked_at = NOW(),
  attempts = attempts + 1,
  updated_at = NOW()
WHERE name = $3
`

type UpdateCompanyJobSiteParams struct {
	WorkingUrl pgtype.Text
	SiteName   pgtype.Text
	Name       string
}

func (q *Queries) UpdateCompanyJobSite(ctx context.Context, arg UpdateCompanyJobSiteParams) error {
	_, err := q.db.Exec(ctx, updateCompanyJobSite, arg.WorkingUrl, arg.SiteName, arg.Name)
	return err
}
