// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deactivateStaleJobs = `-- name: DeactivateStaleJobs :exec
UPDATE jobs
SET active = FALSE
WHERE company_id = $1
  AND last_seen_at < $2
`

type DeactivateStaleJobsParams struct {
	CompanyID       int64
	ScrapeStartedAt pgtype.Timestamptz
}

func (q *Queries) DeactivateStaleJobs(ctx context.Context, arg DeactivateStaleJobsParams) error {
	_, err := q.db.Exec(ctx, deactivateStaleJobs, arg.CompanyID, arg.ScrapeStartedAt)
	return err
}

const insertJob = `-- name: InsertJob :exec
INSERT INTO jobs (company_id, external_id, title, url, location, active, last_seen_at)
VALUES(
  $1,
  $2,
  $3,
  $4,
  $5,
  TRUE,
  NOW()
)
ON CONFLICT (company_id, external_id) DO UPDATE SET
  title = EXCLUDED.title,
  url = EXCLUDED.url,
  location = EXCLUDED.location,
  active = true,
  last_seen_at = NOW()
`

type InsertJobParams struct {
	CompanyID  int64
	ExternalID string
	Title      string
	Url        string
	Location   string
}

func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) error {
	_, err := q.db.Exec(ctx, insertJob,
		arg.CompanyID,
		arg.ExternalID,
		arg.Title,
		arg.Url,
		arg.Location,
	)
	return err
}
