// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Company struct {
	ID               int64
	Name             string
	ShortDescription string
	Size             string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	WorkingUrl       pgtype.Text
	SiteName         pgtype.Text
	LastCheckedAt    pgtype.Timestamptz
	Attempts         int32
}

type WttjScrapeMetaDatum struct {
	ID        int32
	NextPage  int32
	Completed bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
