// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Company struct {
	ID               int64
	Name             string
	ShortDescription string
	Size             string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}
