// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Company struct {
	ID               int64
	Name             string
	UrlSafeName      string
	ShortDescription string
	Size             string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	WorkingUrl       pgtype.Text
	SiteName         pgtype.Text
	LastCheckedAt    pgtype.Timestamptz
	Attempts         int32
	ShouldRetry      bool
	AllSitesChecked  bool
}

type Job struct {
	ID          int64
	CompanyID   int64
	ExternalID  string
	SearchTerm  string
	Title       string
	Url         string
	Location    string
	Active      bool
	FirstSeenAt pgtype.Timestamptz
	LastSeenAt  pgtype.Timestamptz
}

type WttjScrapeMetaDatum struct {
	ID        int32
	NextPage  int32
	Completed bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
