// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wttj_scrape_meta_data.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getWTTJScrapeMetaData = `-- name: GetWTTJScrapeMetaData :one
SELECT next_page, completed, updated_at
FROM wttj_scrape_meta_data
WHERE id = 1
`

type GetWTTJScrapeMetaDataRow struct {
	NextPage  int32
	Completed bool
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetWTTJScrapeMetaData(ctx context.Context) (GetWTTJScrapeMetaDataRow, error) {
	row := q.db.QueryRow(ctx, getWTTJScrapeMetaData)
	var i GetWTTJScrapeMetaDataRow
	err := row.Scan(&i.NextPage, &i.Completed, &i.UpdatedAt)
	return i, err
}

const upsertWTTJScrapeMetaData = `-- name: UpsertWTTJScrapeMetaData :exec
INSERT INTO wttj_scrape_meta_data(id, next_page, completed, updated_at)
VALUES (
  1,
  $1,
  $2,
  NOW()
)
ON CONFLICT (id) DO UPDATE SET
  next_page = EXCLUDED.next_page,
  completed = EXCLUDED.completed,
  updated_at = NOW()
`

type UpsertWTTJScrapeMetaDataParams struct {
	NextPage  int32
	Completed bool
}

func (q *Queries) UpsertWTTJScrapeMetaData(ctx context.Context, arg UpsertWTTJScrapeMetaDataParams) error {
	_, err := q.db.Exec(ctx, upsertWTTJScrapeMetaData, arg.NextPage, arg.Completed)
	return err
}
